# Name of the workflow
name: Scheduled Job

# Define the event that triggers the workflow
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
    #- cron: '0 0 * * *'  # Runs every day at midnight UTC

# Define the jobs to be executed
jobs:
  build-and-test:
    # Name of the job 
    name: Run all unit tests
    # Specify the runner for the job
    runs-on: ubuntu-latest

    # Define the steps to be executed in the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build --configuration Release ./FitNess.UnitTests/FitNess.UnitTests.csproj

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build ./FitNess.UnitTests/FitNess.UnitTests.csproj --logger "trx;LogFileName=testresults.trx"

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: TestResults